config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :orders

  map.resources :sessions

  map.with_options(:controller => "sessions") do |sessions|
    sessions.login "/login", :action => "new"
	  sessions.logout "/logout", :action => "destroy"
	end

  map.resources :users

  map.resources :suppliers

  map.resources :customers

  map.resources :products

  map.resources :categories

  map.resources :units

  map.root :controller => "home"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	validates_presence_of :name
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
	validates_length_of :phone, :in => 7..32, :allow_blank => false
	validates_numericality_of :phone
	validates_format_of :postcode, :with => /\d{8}/
	
	has_and_belongs_to_many :categories, :class_name => "Category", :join_table => "categories_suppliers", :association_foreign_key => "category_id"
	has_and_belongs_to_many :products, :class_name => "Product", :join_table => "products_suppliers", :association_foreign_key => "product_id"
	
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_filter :load_categories_and_products
  # GET /suppliers
  # GET /suppliers.xml
  def index
    @suppliers = Supplier.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @suppliers }
    end
  end

  # GET /suppliers/1
  # GET /suppliers/1.xml
  def show
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @supplier }
    end
  end

  # GET /suppliers/new
  # GET /suppliers/new.xml
  def new
    @supplier = Supplier.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @supplier }
    end
  end

  # GET /suppliers/1/edit
  def edit
    @supplier = Supplier.find(params[:id])
  end

  # POST /suppliers
  # POST /suppliers.xml
  def create
    @supplier = Supplier.new(params[:supplier])

    respond_to do |format|
      if @supplier.save
        flash[:notice] = 'Supplier was successfully created.'
        format.html { redirect_to(@supplier) }
        format.xml  { render :xml => @supplier, :status => :created, :location => @supplier }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @supplier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /suppliers/1
  # PUT /suppliers/1.xml
  def update
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      if @supplier.update_attributes(params[:supplier])
        flash[:notice] = 'Supplier was successfully updated.'
        format.html { redirect_to(@supplier) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @supplier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.xml
  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to(suppliers_url) }
      format.xml  { head :ok }
    end
  end

  def load_categories_and_products
    @categories = Category.find(:all, :order => "name")
    @products = Product.all.map{ |c| [c.id, c.name] }
  end

end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_suppliers_form.html.erb
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :document %><br />
    <%= f.text_field :document %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </p>
  <p>
  	<b>Categories</b><br />
  		<ul>
<% @categories.each do |category| %>
    	<li><%= check_box_tag "supplier[category_ids][]", category.id, @supplier.categories.include?(category), :id => "cat-#{category.id}", :onclick => "marcaProdutos(this.value);" %><%= label_tag "cat-#{category.id}", category.name %>
		<ul>
<%	Product.find(:all, :conditions =>["category_id = ?", category.id], :order => "name").each do |product| %>
			<li><%= check_box_tag "supplier[product_ids][]", product.id, @supplier.products.include?(product), :id => "prod-#{product.id}", :class => "cat-#{category.id}" %><%= label_tag "prod-#{product.id}", product.name %></li>
	<% end %>
		</ul>
	</li>
<% end %>
  		</ul>
</p>
<script type="text/javascript">
	function marcaProdutos(category){
		arr = document.getElementsByTagName('input');
		for(var i=0; i<arr.length; i++){
			obj = arr[i];
			if(obj.className == 'cat-'+category){
				obj.checked='checked';

			}
		}
	}
</script>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<% form_for(@supplier) do |f| %>
  <%= f.error_messages %>

	<%= render :partial => 'suppliers_form', :locals => {:f => f} %>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<h1>Listing suppliers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Document</th>
    <th>Email</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Phone</th>
    <th>Postcode</th>
  </tr>

<% for supplier in @suppliers %>
  <tr>
    <td><%=h supplier.name %></td>
    <td><%=h supplier.document %></td>
    <td><%=h supplier.email %></td>
    <td><%=h supplier.address %></td>
    <td><%=h supplier.city %></td>
    <td><%=h supplier.state %></td>
    <td><%=h supplier.phone %></td>
    <td><%=h supplier.postcode %></td>
    <td><%= link_to 'Show', supplier %></td>
    <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
    <td><%= link_to 'Destroy', supplier, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<% form_for(@supplier) do |f| %>
  <%= f.error_messages %>

	<%= render :partial => 'suppliers_form', :locals => {:f => f} %>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p>
  <b>Name:</b>
  <%=h @supplier.name %>
</p>

<p>
  <b>Document:</b>
  <%=h @supplier.document %>
</p>

<p>
  <b>Email:</b>
  <%=h @supplier.email %>
</p>

<p>
  <b>Address:</b>
  <%=h @supplier.address %>
</p>

<p>
  <b>City:</b>
  <%=h @supplier.city %>
</p>

<p>
  <b>State:</b>
  <%=h @supplier.state %>
</p>

<p>
  <b>Phone:</b>
  <%=h @supplier.phone %>
</p>

<p>
  <b>Postcode:</b>
  <%=h @supplier.postcode %>
</p>

<% unless @supplier.categories.empty? %>
  <p>
    <b>Categories:</b>
    <ul>
      <% @supplier.categories.each do |category| %>
        <li><%=h category.name %>
		<ul>
      <% @supplier.products.each do |product| %>
	<% if product.category_id == category.id then %>
			<li><%=h product.name %></li>
	 <% end %>
      <% end %>
		</ul>
	</li>
      <% end %>
    </ul>
  </p>
<% end %>


<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>